Public Class Startup

    Private Sub btnHumanPlayerRandomName_Click(sender As System.Object, e As System.EventArgs) Handles btnHumanPlayerRandomName.Click
        Dim PlayerName As String = String.Empty
        Do
            PlayerName = GetRandomCountryName()
        Loop Until PlayerName <> Me.txtAIName.Text
        Me.txtPlayerName.Text = PlayerName
    End Sub

    Private Sub btnAIPlayerRandomName_Click(sender As System.Object, e As System.EventArgs) Handles btnAIPlayerRandomName.Click
        Dim PlayerName As String = String.Empty
        Do
            PlayerName = GetRandomCountryName()
        Loop Until PlayerName <> Me.txtPlayerName.Text
        Me.txtAIName.Text = PlayerName
    End Sub

    Private Function GetRandomCountryName() As String

        Dim rng As New Random(System.DateTime.Now.Millisecond)

        Dim Countries As New List(Of String)
        Countries.Add("Afghanistan")
        Countries.Add("Albania")
        Countries.Add("Algeria")
        Countries.Add("Andorra")
        Countries.Add("Angola")
        Countries.Add("Antigua")
        Countries.Add("Argentina")
        Countries.Add("Armenia")
        Countries.Add("Australia")
        Countries.Add("Austria")
        Countries.Add("Azerbaijan")
        Countries.Add("Bahamas")
        Countries.Add("Bahrain")
        Countries.Add("Bangladesh")
        Countries.Add("Barbados")
        Countries.Add("Belarus")
        Countries.Add("Belgium")
        Countries.Add("Belize")
        Countries.Add("Benin")
        Countries.Add("Bhutan")
        Countries.Add("Bolivia")
        Countries.Add("Bosnia Herzegovina")
        Countries.Add("Botswana")
        Countries.Add("Brazil")
        Countries.Add("Brunei")
        Countries.Add("Bulgaria")
        Countries.Add("Burkina")
        Countries.Add("Burundi")
        Countries.Add("Cambodia")
        Countries.Add("Cameroon")
        Countries.Add("Canada")
        Countries.Add("Cape Verde")
        Countries.Add("Central African Rep")
        Countries.Add("Chad")
        Countries.Add("Chile")
        Countries.Add("China")
        Countries.Add("Colombia")
        Countries.Add("Comoros")
        Countries.Add("Congo")
        Countries.Add("Congo")
        Countries.Add("Costa Rica")
        Countries.Add("Croatia")
        Countries.Add("Cuba")
        Countries.Add("Cyprus")
        Countries.Add("Czech Republic")
        Countries.Add("Denmark")
        Countries.Add("Djibouti")
        Countries.Add("Dominica")
        Countries.Add("Dominican Republic")
        Countries.Add("East Timor")
        Countries.Add("Ecuador")
        Countries.Add("Egypt")
        Countries.Add("El Salvador")
        Countries.Add("Equatorial Guinea")
        Countries.Add("Eritrea")
        Countries.Add("Estonia")
        Countries.Add("Ethiopia")
        Countries.Add("Fiji")
        Countries.Add("Finland")
        Countries.Add("France")
        Countries.Add("Gabon")
        Countries.Add("Gambia")
        Countries.Add("Georgia")
        Countries.Add("Germany")
        Countries.Add("Ghana")
        Countries.Add("Greece")
        Countries.Add("Grenada")
        Countries.Add("Guatemala")
        Countries.Add("Guinea")
        Countries.Add("Guinea-Bissau")
        Countries.Add("Guyana")
        Countries.Add("Haiti")
        Countries.Add("Honduras")
        Countries.Add("Hungary")
        Countries.Add("Iceland")
        Countries.Add("India")
        Countries.Add("Indonesia")
        Countries.Add("Iran")
        Countries.Add("Iraq")
        Countries.Add("Ireland")
        Countries.Add("Israel")
        Countries.Add("Italy")
        Countries.Add("Ivory Coast")
        Countries.Add("Jamaica")
        Countries.Add("Japan")
        Countries.Add("Jordan")
        Countries.Add("Kazakhstan")
        Countries.Add("Kenya")
        Countries.Add("Kiribati")
        Countries.Add("Korea North")
        Countries.Add("Korea South")
        Countries.Add("Kosovo")
        Countries.Add("Kuwait")
        Countries.Add("Kyrgyzstan")
        Countries.Add("Laos")
        Countries.Add("Latvia")
        Countries.Add("Lebanon")
        Countries.Add("Lesotho")
        Countries.Add("Liberia")
        Countries.Add("Libya")
        Countries.Add("Liechtenstein")
        Countries.Add("Lithuania")
        Countries.Add("Luxembourg")
        Countries.Add("Macedonia")
        Countries.Add("Madagascar")
        Countries.Add("Malawi")
        Countries.Add("Malaysia")
        Countries.Add("Maldives")
        Countries.Add("Mali")
        Countries.Add("Malta")
        Countries.Add("Marshall Islands")
        Countries.Add("Mauritania")
        Countries.Add("Mauritius")
        Countries.Add("Mexico")
        Countries.Add("Micronesia")
        Countries.Add("Moldova")
        Countries.Add("Monaco")
        Countries.Add("Mongolia")
        Countries.Add("Montenegro")
        Countries.Add("Morocco")
        Countries.Add("Mozambique")
        Countries.Add("Myanmar")
        Countries.Add("Namibia")
        Countries.Add("Nauru")
        Countries.Add("Nepal")
        Countries.Add("Netherlands")
        Countries.Add("New Zealand")
        Countries.Add("Nicaragua")
        Countries.Add("Niger")
        Countries.Add("Nigeria")
        Countries.Add("Norway")
        Countries.Add("Oman")
        Countries.Add("Pakistan")
        Countries.Add("Palau")
        Countries.Add("Panama")
        Countries.Add("Papua New Guinea")
        Countries.Add("Paraguay")
        Countries.Add("Peru")
        Countries.Add("Philippines")
        Countries.Add("Poland")
        Countries.Add("Portugal")
        Countries.Add("Qatar")
        Countries.Add("Romania")
        Countries.Add("Russian Federation")
        Countries.Add("Rwanda")
        Countries.Add("St Kitts & Nevis")
        Countries.Add("St Lucia")
        Countries.Add("Saint Vincent & the Grenadines")
        Countries.Add("Samoa")
        Countries.Add("San Marino")
        Countries.Add("Sao Tome & Principe")
        Countries.Add("Saudi Arabia")
        Countries.Add("Senegal")
        Countries.Add("Serbia")
        Countries.Add("Seychelles")
        Countries.Add("Sierra Leone")
        Countries.Add("Singapore")
        Countries.Add("Slovakia")
        Countries.Add("Slovenia")
        Countries.Add("Solomon Islands")
        Countries.Add("Somalia")
        Countries.Add("South Africa")
        Countries.Add("South Sudan")
        Countries.Add("Spain")
        Countries.Add("Sri Lanka")
        Countries.Add("Sudan")
        Countries.Add("Suriname")
        Countries.Add("Swaziland")
        Countries.Add("Sweden")
        Countries.Add("Switzerland")
        Countries.Add("Syria")
        Countries.Add("Taiwan")
        Countries.Add("Tajikistan")
        Countries.Add("Tanzania")
        Countries.Add("Thailand")
        Countries.Add("Togo")
        Countries.Add("Tonga")
        Countries.Add("Trinidad")
        Countries.Add("Tobago")
        Countries.Add("Tunisia")
        Countries.Add("Turkey")
        Countries.Add("Turkmenistan")
        Countries.Add("Tuvalu")
        Countries.Add("Uganda")
        Countries.Add("Ukraine")
        Countries.Add("United Arab Emirates")
        Countries.Add("United Kingdom")
        Countries.Add("United States")
        Countries.Add("Uruguay")
        Countries.Add("Uzbekistan")
        Countries.Add("Vanuatu")
        Countries.Add("Vatican City")
        Countries.Add("Venezuela")
        Countries.Add("Vietnam")
        Countries.Add("Yemen")
        Countries.Add("Zambia")
        Countries.Add("Zimbabwe")

        Return Countries(rng.Next(0, Countries.Count - 1))
    End Function

    Private Sub btnStart_Click(sender As System.Object, e As System.EventArgs) Handles btnStart.Click

        Main.PlayerCountryName = txtPlayerName.Text
        Main.AICountryName = txtAIName.Text
        Me.Hide()
        Main.Show()


    End Sub
End Class
